---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: "Include diademiemi.template"
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
