name: Molecule

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: $(echo ${{ github.repository }} | cut -d/ -f2 | sed -r "s/ansible_(role|collection)_//g" | sed "s,\.,/,g")

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies.
        run: pip3 install yamllint ansible-lint ansible molecule "molecule-plugins[docker]"

      - name: Install Galaxy dependencies.
        run: ansible-galaxy collection install community.docker

      - name: Run molecule
        run: >-
          pwd && ls &&
          cd $(echo ${{ github.repository }} | cut -d/ -f2 | sed -r "s/ansible_(role|collection)_//g" | sed "s,\.,/,g") &&
          molecule test
